import { AccountTemplate } from '../types/accounts.types';

export const PROFESSIONAL_SERVICES_TEMPLATE: AccountTemplate[] = [
  { accountNumber: '1000', name: 'Cash and Cash Equivalents', type: 'current_assets', detailType: 'Cash', isSubAccount: false },
  { accountNumber: '1010', name: 'Business Checking', type: 'current_assets', detailType: 'Checking', isSubAccount: true, parentName: 'Cash and Cash Equivalents' },
  { accountNumber: '1020', name: 'Business Savings', type: 'current_assets', detailType: 'Savings', isSubAccount: true, parentName: 'Cash and Cash Equivalents' },
  { accountNumber: '1100', name: 'Accounts Receivable', type: 'current_assets', detailType: 'Accounts Receivable', isSubAccount: false },
  { accountNumber: '1200', name: 'Undeposited Funds', type: 'current_assets', detailType: 'Undeposited Funds', isSubAccount: false },
  { accountNumber: '1300', name: 'Prepaid Expenses', type: 'current_assets', detailType: 'Prepaid Expenses', isSubAccount: false },
  { accountNumber: '1500', name: 'Office Equipment', type: 'fixed_assets', detailType: 'Furniture & Equipment', isSubAccount: false },
  { accountNumber: '1510', name: 'Computer Equipment', type: 'fixed_assets', detailType: 'Furniture & Equipment', isSubAccount: false },
  { accountNumber: '1600', name: 'Accumulated Depreciation', type: 'fixed_assets', detailType: 'Accumulated Depreciation', isSubAccount: false },
  { accountNumber: '2000', name: 'Accounts Payable', type: 'current_liabilities', detailType: 'Accounts Payable', isSubAccount: false },
  { accountNumber: '2100', name: 'Credit Card Payable', type: 'current_liabilities', detailType: 'Credit Card', isSubAccount: false },
  { accountNumber: '2200', name: 'Accrued Liabilities', type: 'current_liabilities', detailType: 'Other Current Liabilities', isSubAccount: false },
  { accountNumber: '2300', name: 'Payroll Liabilities', type: 'current_liabilities', detailType: 'Payroll Liabilities', isSubAccount: false },
  { accountNumber: '2400', name: 'Sales Tax Payable', type: 'current_liabilities', detailType: 'Sales Tax Payable', isSubAccount: false },
  { accountNumber: '2500', name: 'Unearned Revenue', type: 'current_liabilities', detailType: 'Unearned Revenue', isSubAccount: false },
  { accountNumber: '3000', name: 'Opening Balance Equity', type: 'equity', detailType: 'Opening Balance Equity', isSubAccount: false },
  { accountNumber: '3100', name: "Owner's Equity", type: 'equity', detailType: "Owner's Equity", isSubAccount: false },
  { accountNumber: '3200', name: 'Retained Earnings', type: 'equity', detailType: 'Retained Earnings', isSubAccount: false },
  { accountNumber: '4000', name: 'Service Revenue', type: 'revenue', detailType: 'Service Revenue', isSubAccount: false },
  { accountNumber: '4010', name: 'Consulting Revenue', type: 'revenue', detailType: 'Service Revenue', isSubAccount: true, parentName: 'Service Revenue' },
  { accountNumber: '4020', name: 'Project Revenue', type: 'revenue', detailType: 'Service Revenue', isSubAccount: true, parentName: 'Service Revenue' },
  { accountNumber: '4100', name: 'Reimbursable Revenue', type: 'revenue', detailType: 'Service Revenue', isSubAccount: false },
  { accountNumber: '4900', name: 'Other Income', type: 'other_income', detailType: 'Other Income', isSubAccount: false },
  { accountNumber: '4910', name: 'Interest Income', type: 'other_income', detailType: 'Interest Earned', isSubAccount: false },
  { accountNumber: '5000', name: 'Cost of Services', type: 'cost_of_goods_sold', detailType: 'Cost of Services', isSubAccount: false },
  { accountNumber: '5010', name: 'Subcontractor Costs', type: 'cost_of_goods_sold', detailType: 'Subcontracted Services', isSubAccount: true, parentName: 'Cost of Services' },
  { accountNumber: '6000', name: 'Advertising & Marketing', type: 'expenses', detailType: 'Advertising', isSubAccount: false },
  { accountNumber: '6100', name: 'Bank Charges & Fees', type: 'expenses', detailType: 'Bank Charges', isSubAccount: false },
  { accountNumber: '6200', name: 'Insurance', type: 'expenses', detailType: 'Insurance', isSubAccount: false },
  { accountNumber: '6300', name: 'Office Supplies', type: 'expenses', detailType: 'Office Supplies', isSubAccount: false },
  { accountNumber: '6400', name: 'Professional Development', type: 'expenses', detailType: 'Training', isSubAccount: false },
  { accountNumber: '6500', name: 'Professional Fees', type: 'expenses', detailType: 'Legal & Professional', isSubAccount: false },
  { accountNumber: '6600', name: 'Rent & Lease', type: 'expenses', detailType: 'Rent or Lease', isSubAccount: false },
  { accountNumber: '6700', name: 'Software & Subscriptions', type: 'expenses', detailType: 'Software', isSubAccount: false },
  { accountNumber: '6800', name: 'Telephone & Internet', type: 'expenses', detailType: 'Utilities', isSubAccount: false },
  { accountNumber: '6900', name: 'Travel & Entertainment', type: 'expenses', detailType: 'Travel', isSubAccount: false },
  { accountNumber: '7000', name: 'Salaries & Wages', type: 'expenses', detailType: 'Payroll Expenses', isSubAccount: false },
  { accountNumber: '7100', name: 'Payroll Taxes', type: 'expenses', detailType: 'Payroll Expenses', isSubAccount: false },
  { accountNumber: '7200', name: 'Employee Benefits', type: 'expenses', detailType: 'Employee Benefits', isSubAccount: false },
  { accountNumber: '7300', name: 'Depreciation Expense', type: 'expenses', detailType: 'Depreciation', isSubAccount: false },
  { accountNumber: '7400', name: 'Utilities', type: 'expenses', detailType: 'Utilities', isSubAccount: false },
  { accountNumber: '7500', name: 'Miscellaneous Expense', type: 'expenses', detailType: 'Other Expense', isSubAccount: false },
  { accountNumber: '8000', name: 'Currency Gain/Loss', type: 'other_expenses', detailType: 'Exchange Gain or Loss', isSubAccount: false },
];

export const ACCOUNT_TEMPLATES: Record<string, AccountTemplate[]> = {
  professional_services: PROFESSIONAL_SERVICES_TEMPLATE,
  consulting: PROFESSIONAL_SERVICES_TEMPLATE,
  technology: PROFESSIONAL_SERVICES_TEMPLATE,
};
